---
- name: "Setup Linux, Nginx, MySQL, PHP (LEMP stack)"
  hosts: "server1"  # Mendefinisikan host di mana playbook akan dijalankan, yaitu server1
  become: true  # Menentukan bahwa tugas-tugas harus dijalankan dengan hak akses root

  tasks:  # Bagian ini mendefinisikan daftar tugas yang akan dijalankan pada host
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes  # Mengupdate cache paket apt
        upgrade: dist  # Mengupgrade semua paket yang terinstal ke versi terbaru yang tersedia

    - name: Install common packages
      apt:
        name: "{{ item }}"  # Menentukan paket yang akan diinstal
        state: present  # Pastikan paket dalam keadaan terinstal
      loop:
        - curl  # Daftar paket yang akan diinstal
        - gnupg
        - software-properties-common
        - unzip

    - name: Install Nginx
      apt:
        name: nginx  # Menentukan bahwa Nginx harus diinstal
        state: present  # Pastikan Nginx dalam keadaan terinstal

    - name: Ensure Nginx is running
      service:
        name: nginx  # Nama layanan yang harus dijalankan
        state: started  # Pastikan layanan sedang berjalan
        enabled: yes  # Pastikan layanan diatur untuk dimulai saat boot

    - name: Install PyMySQL
      apt:
        name: python3-pymysql  # Menentukan bahwa PyMySQL harus diinstal
        state: present  # Pastikan PyMySQL dalam keadaan terinstal
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"  # Kondisional, hanya jika sistem adalah Ubuntu atau Debian

    - name: Install PyMySQL
      yum:
        name: python3-PyMySQL  # Menentukan bahwa PyMySQL harus diinstal
        state: present  # Pastikan PyMySQL dalam keadaan terinstal
      when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"  # Kondisional, hanya jika sistem adalah CentOS atau RedHat

    - name: Install MySQL server
      apt:
        name: mysql-server  # Menentukan bahwa MySQL server harus diinstal
        state: present  # Pastikan MySQL server dalam keadaan terinstal
        force: yes  # Memaksa instalasi, bahkan jika ada konflik
        install_recommends: no  # Jangan menginstal paket yang direkomendasikan

    - name: Ensure MySQL is running
      service:
        name: mysql  # Nama layanan yang harus dijalankan
        state: started  # Pastikan layanan sedang berjalan
        enabled: yes  # Pastikan layanan diatur untuk dimulai saat boot

    - name: Set MySQL root password
      mysql_user:
        name: root  # Nama pengguna MySQL yang akan diubah atau dibuat
        password:  # Kata sandi baru untuk pengguna root
        login_unix_socket: /var/run/mysqld/mysqld.sock  # Jalur soket UNIX untuk login MySQL
        state: present  # Pastikan pengguna dalam keadaan ada

    - name: Remove Apache2 if installed
      apt:
        name: apache2*  # Menentukan bahwa semua paket yang dimulai dengan apache2 harus dihapus
        state: absent  # Pastikan paket dalam keadaan tidak terinstal

    - name: Add PHP PPA repository
      apt_repository:
        repo: ppa:ondrej/php  # Menambahkan repository PPA untuk versi PHP terbaru
        state: present  # Pastikan repository dalam keadaan ada

    - name: Install PHP 8.3 and common extensions
      apt:
        name: "{{ item }}"  # Menentukan paket PHP yang akan diinstal
        state: present  # Pastikan paket dalam keadaan terinstal
      loop:
        - php8.3  # Daftar paket PHP yang akan diinstal
        - php8.3-fpm
        - php8.3-mysql
        - php8.3-xml
        - php8.3-cli
        - php8.3-curl
        - php8.3-mbstring

    - name: Ensure PHP-FPM is running
      service:
        name: php8.3-fpm  # Nama layanan PHP-FPM yang harus dijalankan
        state: started  # Pastikan layanan sedang berjalan
        enabled: yes  # Pastikan layanan diatur untuk dimulai saat boot
